DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS entry;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE entry (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  start DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  finish DATETIME NOT NULL,
  duration INTEGER NOT NULL,
  project_title TEXT NOT NULL,
  complexity INTEGER NOT NULL,
  project_complete BOOLEAN NOT NULL,
  summary TEXT NOT NULL,
  task_num INTEGER NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
